default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # 追記
  template: template0

development:
  <<: *default
  database: sesion_login_development

test:
  <<: *default
  database: sesion_login_test

production:
  <<: *default
  database: sesion_login_production
  username: sesion_login
  password: <%= ENV['SESION_LOGIN_DATABASE_PASSWORD'] %>
